[phases.setup]
nixPkgs = ['...', 'python39', 'python312Packages.setuptools', 'gccStdenv']
aptPkgs = ['build-essential', 'libcairo2-dev', 'libpango1.0-dev', 'libjpeg-dev', 'libgif-dev', 'librsvg2-dev']

[phases.build]
cmds = ["bun run build-prod"]

[start]
cmd = "bun run start-built"
