[phases.setup]
nixPkgs = [
    '...',
    '(python3.withPackages (python-pkgs: [ python-pkgs.setuptools]))',
    'gccStdenv',
]
aptPkgs = [
    'build-essential',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libjpeg-dev',
    'libgif-dev',
    'librsvg2-dev',
    'libstdc++6'
]

[phases.build]
cmds = ["bun run build-prod"]

[start]
cmd = "bun run start-built"
